import type { Metadata } from "next";
import { JetBrains_Mono, Syne } from "next/font/google";
import "./globals.css";
import { ThirdwebProvider } from "thirdweb/react";
import NavBar from "./Components/Navbar";
import Footer from "./Components/Footer";

const syne = Syne({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const mono = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PokeEvolve",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${syne.variable} ${mono.className} ${mono.variable} antialiased`}
      >
        <ThirdwebProvider>
          <NavBar />
          {children}
          <Footer />
        </ThirdwebProvider>
      </body>
    </html>
  );
}
